development:
  adapter: mysql2
  database: bookstore_api_dev
  username: root
  password: password
  encoding: utf8
  host: localhost
  reconnect: <%= ENV['RAILS_RECONNECT_DB'] || false %>
  pool: 5
  socket: /tmp/mysql.sock