development:
# Generated keys using SecureRandom.base64
  bookstore_api_key: luUKD8qYtRVOJMmvPz1l4Q==
  bookstore_secret_key: dSXmXk/r7lqE74fKRZx8PA==
test:
  bookstore_api_key: luUKD8qYtRVOJMmvPz1l4Q==
  bookstore_secret_key: dSXmXk/r7lqE74fKRZx8PA==